<?xml version="1.0" encoding="utf-8"?><Database Name="db_sistema" Class="sistemaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-SFE7UO1\SQLEXPRESS;Initial Catalog=db_sistema;Integrated Security=True" SettingsObjectName="Sistema.DAL.Properties.Settings" SettingsPropertyName="db_sistemaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_categoria" Member="Categoria">
    <Type Name="Categoria">
      <Column Name="id_categoria" Member="Codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="desc_categoria" Member="Descrição" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tb_categoria_tb_produto" Member="Produto" ThisKey="Codigo" OtherKey="Codigo" Type="Produto" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.tb_produto" Member="Produto">
    <Type Name="Produto">
      <Column Name="id_produto" Member="Codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="desc_produto" Member="Descrição" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="valor" Member="Valor" Type="System.Decimal" DbType="Decimal(25,2)" CanBeNull="true" />
      <Column Name="id_categoria" Member="CodigoCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_categoria_tb_produto" Member="Categoria" ThisKey="Codigo" OtherKey="Codigo" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
</Database>